export const timelineInfo = [
  {
    left: "15%",
    ClassName: "data_cir cir_0",
    date: "Q2 2022",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: true,
    TextTowLi1: "Phase 1&2 - Launch Cycle",
    TextTowLi2: "Whitepaper & Token Model",
    IsThreeLi: false,
    TextThreeLi1: "",
    TextThreeLi2: "",
    TextThreeLi3: "",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-regular fa-magnifying-glass-dollar fa-2x fa-primary",
  },
  {
    left: "26%",
    ClassName: "data_cir cir_1 next",
    date: "Q3 2022",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: true,
    TextTowLi1: "Phase 3 to 10 - NFT mint",
    TextTowLi2: "Station deployments & network operation",
    IsThreeLi: false,
    TextThreeLi1: "",
    TextThreeLi2: "",
    TextThreeLi3: "",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-regular fa-layer-group fa-2x fa-primary",
  },
  {
    left: "38%",
    ClassName: "data_cir cir_2 next",
    date: "Q4 2022",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: true,
    TextTowLi1: "NFT Staking",
    TextTowLi2: "Station deployments & network operation",
    IsThreeLi: false,
    TextThreeLi1: "",
    TextThreeLi2: "",
    TextThreeLi3: "",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-regular fa-cart-arrow-down fa-2x fa-primary",
  },
  {
    left: "50%",
    ClassName: "data_cir cir_3 next",
    date: "Q1 2023",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: false,
    TextTowLi1: "",
    TextTowLi2: "",
    IsThreeLi: true,
    TextThreeLi1: "Public sale (DEX)",
    TextThreeLi2: "RFID card setup",
    TextThreeLi3: "Station deployments & network operation",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-regular fa-id-card-clip fa-2x fa-primary",
  },
  {
    left: "62%",
    ClassName: "data_cir cir_4 red_c next",
    date: "Q2 2023",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: true,
    TextTowLi1: "Partnership Campaign",
    TextTowLi2: "Station deployments & network operation",
    IsThreeLi: false,
    TextThreeLi1: "",
    TextThreeLi2: "",
    TextThreeLi3: "",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-regular fa-network-wired fa-2x fa-primary",
  },
  {
    left: "74%",
    ClassName: "data_cir cir_5 next",
    date: "Q1 2024",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: false,
    TextTowLi1: "",
    TextTowLi2: "",
    IsThreeLi: true,
    TextThreeLi1: "DAO",
    TextThreeLi2: "Governance",
    TextThreeLi3: "Station deployments & network operation",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-solid fa-users fa-2x fa-primary",
  },
  {
    left: "85%",
    ClassName: "data_cir cir_6 next",
    date: "Q2 2030",
    IsSpan: false,
    TextSpan: "",
    IsTowLi: true,
    TextTowLi1: "10,000+",
    TextTowLi2: "EV network expansion",
    IsThreeLi: false,
    TextThreeLi1: "",
    TextThreeLi2: "",
    TextThreeLi3: "",
    IsFourLi: false,
    TextFourLi1: "",
    TextFourLi2: "",
    TextFourLi3: "",
    TextFourLi4: "",
    img: "fa-solid fa-arrow-trend-up fa-2x fa-primary",
  },
];

export const VerticalSocial = [
  // {
  //   nameIco: "fa-brands fa-telegram",
  //   extlink: "https://t.me/+J7PBUzXHlUcyM2Ex",
  //   key: "1",
  // },
  // { nameIco: "fa-brands fa-discord", extlink: "/", key: "2" },
  {
    nameIco: "fa-brands fa-tiktok",
    extlink: "https://www.tiktok.com/@ev_initiative",
    key: "1",
  },
  {
    nameIco: "fa-brands fa-twitter",
    extlink: "https://twitter.com/EV_Initiative",
    key: "2",
  },
  {
    nameIco: "fa-brands fa-instagram",
    extlink: "https://www.instagram.com/ev_initiative/",
    key: "3",
  },
  {
    nameIco: "fa-brands fa-linkedin-in",
    extlink: "https://www.linkedin.com/company/ev-initiative/about/",
    key: "4",
  },
];
